### ISSUE TITLE
Let's Encrypt certificate is not supported

### ISSUE THREAD

**Issue by guerda** [binwiederhier/ntfy-android#107]
I installed ntfy-android from F-Droid in version 1.16.0.
The app works fine with ntfy.sh  but not with my self-hosted installation.

When I want to subscribe to a new topic and enter my own server, it says:

   ```
   java.security.cert.CertPathValidatorException: Trust anchor for certification path  not found.
   ```

<img alt="Screenshof of ntfy Android and it's subscribe dialog. Error message as above" src="https://github.com/user-attachments/assets/4cb16180-1b77-4223-81d8-5b4b6d6fd679" width="300" />

The certificate is issued via Let's Encrypt and has a wildcard for subdomains.

In multiple browsers on multiple defvices, the URL works fine (Chrome, Firefox, macos, Android)
Any idea if this is a bug or misconfiguration on my end?

I'm hosting it with Docker Compose and behind Caddy. I followed those docs: 
https://docs.ntfy.sh/config/#__tabbed_11_4

# Caddy config

```
ntfy.example.com
  reverse_proxy :8002
  # Redirect HTTP to HTTPS, but only for GET topic addresses, since we want
  # it to work with curl without the annoying https:// prefix
  @httpget {
    protocol http
    method GET
    path_regexp ^/([-_a-z0-9]{0,64}$|docs/|static/)
  }
  redir @httpget https://{host}{uri}
}
```

# Docker compose

```
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Berlin    # optional: set desired timezone
      - user=1001:1002 # optional: replace with your own user/group or uid/gid
      - NTFY_BASE_URL=https://ntfy.example.com
      - NTFY_BEHIND_PROXY=true
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/etc/ntfy/auth.db

    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 8002:80
    restart: unless-stopped
```

https://nopaste.net/pSrsFMBZWl
